[variables]
# Force Python 3.10 - Multiple enforcement methods
NIXPACKS_PYTHON_VERSION = "3.10"
PYTHON_VERSION = "3.10"
PYTHON_RUNTIME_VERSION = "3.10"

# Increase build timeout for heavy dependencies
NIXPACKS_BUILD_TIMEOUT = "1800"

# Memory and performance optimization
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
PIP_NO_CACHE_DIR = "1"
PIP_DISABLE_PIP_VERSION_CHECK = "1"

[phases.setup]
cmds = [
  "apt-get update",
  "apt-get install -y software-properties-common",
  "add-apt-repository ppa:deadsnakes/ppa -y",
  "apt-get update",
  "apt-get install -y python3.10 python3.10-dev python3.10-distutils python3.10-venv",
  "apt-get install -y build-essential gcc g++ gfortran libopenblas-dev liblapack-dev pkg-config",
  "update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1",
  "update-alternatives --install /usr/bin/pip3 pip3 /usr/bin/pip3 1"
]

[phases.install]
cmds = [
  "python3.10 -m pip install --upgrade pip setuptools wheel",
  "python3.10 -m pip install --no-cache-dir --only-binary=:all: --timeout 300 -r requirements.txt"
]

[phases.build]
cmds = [
  "python3.10 -c 'import sys; print(f\"Python version: {sys.version}\")'",
  "python3.10 -c 'import numpy; import pandas; import backtrader; print(\"Dependencies verified\")'"
]

[phases.start]
cmd = "gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 app:app"

[providers.python]
version = "3.10"