# Binance API Configuration
api:
  api_key: "YOUR_BINANCE_API_KEY"  # Replace with your actual API key
  api_secret: "YOUR_BINANCE_SECRET_KEY"  # Replace with your actual secret key
  testnet: true  # Set to false for live trading
  base_url: "https://testnet.binance.vision"  # Testnet URL

# Trading Configuration
trading:
  symbol: "BTCUSDT"
  capital: 30.0  # Total capital in USDT
  risk_per_trade: 0.01  # 1% risk per trade
  max_position_size: 0.30  # Maximum $0.30 per trade
  
# Strategy Parameters
strategy:
  type: mean_reversion  # Options: mean_reversion, grid, dca
  sma_period: 20
  entry_threshold: 0.005  # 0.5% below SMA to buy
  exit_threshold: 0.005   # 0.5% above SMA to sell
  stop_loss: 0.008        # 0.8% stop loss
  
  # Enhanced indicators
  params:
    rsi_period: 14
    bb_period: 20
    bb_std: 2
    
    # Grid strategy parameters
    grid_levels: 10
    grid_range: 0.05  # 5% range
    grid_risk_per_order: 0.001  # 0.1% risk per grid order
    
    # DCA strategy parameters
    dca_interval: weekly
    dca_amount: 10.0  # $10 per DCA
    dca_trigger: -0.02  # -2% price drop trigger
  
# Risk Management
risk:
  max_daily_trades: 5
  max_daily_loss: 1.0  # Maximum daily loss in USDT
  cooldown_period: 300  # 5 minutes between trades
  
# AI Configuration
ai:
  openrouter: true  # Enable/disable OpenRouter AI features
  frequency: 15m    # AI analysis frequency

# Monitoring and alerts
monitoring:
  log_level: INFO
  performance_threshold: 0.05  # 5% performance drop alert
  balance_alert_threshold: 0.1  # Alert if balance drops 10%
  
# Backtesting
backtest:
  start_date: "2024-01-01"
  end_date: "2024-12-31"
  initial_cash: 30.0
  commission: 0.001  # 0.1% trading fee